# Generated by Django 5.0 on 2024-01-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='subcategory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
