# Generated by Django 5.0 on 2024-01-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_component_category_component_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='subcategory',
        ),
    ]
