# Generated by Django 5.0 on 2024-01-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_component_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval',
            field=models.CharField(choices=[('approved', 'Approved'), ('not approved', 'Not Approved')], default='not approved', max_length=20),
        ),
    ]
